In [1]:
import pandas as P

In [2]:
import numpy as N

In [3]:
dataset = P.read_csv('../50_Startups.csv')

In [4]:
#dataset

In [5]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [6]:
y = dataset['Profit']

In [7]:
#y

In [8]:
X = dataset[['R&D Spend', 'Administration', 'Marketing Spend', 'State']]

In [9]:
#X

In [10]:
X.shape

(50, 4)

In [11]:
y.shape

(50,)

In [12]:
type(y)

pandas.core.series.Series

In [13]:
y = y.values

In [14]:
type(y)

numpy.ndarray

In [15]:
y.reshape(1,-1)

array([[192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
        156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
        141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
        124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
        108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
         99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
         90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
         71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
         35673.41,  14681.4 ]])

In [16]:
type(y)

numpy.ndarray

In [17]:
y.shape

(50,)

In [18]:
#y.reshape(-1,1)

In [19]:
state = X['State']

In [20]:
#state

# Now we have a string in our dataset so we have to convert the names into digits so that the computers can understand
  
  for this we use LabelEncoder library

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
state_le = LabelEncoder()

In [23]:
state = state_le.fit_transform(state)

In [24]:
state

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0])

In [25]:
state.shape

(50,)

In [26]:
import numpy

In [27]:
#state = state.reshape(-1,1)

In [28]:
type(state)

numpy.ndarray

In [29]:
state.shape

(50,)

In [30]:
X = X.values

In [31]:
type(X)

numpy.ndarray

In [32]:
X.shape

(50, 4)

In [33]:
type(X)

numpy.ndarray

In [34]:
X[:,3] = state

In [40]:
X = X[:,0:3]

In [41]:
X

array([[165349.2, 136897.8, 471784.1],
       [162597.7, 151377.59, 443898.53],
       [153441.51, 101145.55, 407934.54],
       [144372.41, 118671.85, 383199.62],
       [142107.34, 91391.77, 366168.42],
       [131876.9, 99814.71, 362861.36],
       [134615.46, 147198.87, 127716.82],
       [130298.13, 145530.06, 323876.68],
       [120542.52, 148718.95, 311613.29],
       [123334.88, 108679.17, 304981.62],
       [101913.08, 110594.11, 229160.95],
       [100671.96, 91790.61, 249744.55],
       [93863.75, 127320.38, 249839.44],
       [91992.39, 135495.07, 252664.93],
       [119943.24, 156547.42, 256512.92],
       [114523.61, 122616.84, 261776.23],
       [78013.11, 121597.55, 264346.06],
       [94657.16, 145077.58, 282574.31],
       [91749.16, 114175.79, 294919.57],
       [86419.7, 153514.11, 0.0],
       [76253.86, 113867.3, 298664.47],
       [78389.47, 153773.43, 299737.29],
       [73994.56, 122782.75, 303319.26],
       [67532.53, 105751.03, 304768.73],
       [77044.01, 

In [42]:
X.shape

(50, 3)

In [43]:
from sklearn.linear_model import LinearRegression

In [44]:
model = LinearRegression()

In [45]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [46]:
model.coef_

array([ 0.80571505, -0.02681597,  0.02722806])

# Now that we have found out about the coefficient  there is a problem in the weight of state. We have a weight of the state feature but it doesn't make any sense as it does not specify the weight of indivisual state but the states as whole

 -> Now we have to make sure that we find the weight of all the states indivisually and for this we will use --
          -->> OneHotEncoding feature od sklearn . preprocessing class

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
state_ohe = OneHotEncoder()

In [49]:
#first we have to convert the state into 2-d array
state = state.reshape(-1,1)

In [50]:
state.shape

(50, 1)

In [51]:
state_dummy = state_ohe.fit_transform(state)

In [52]:
state_dummy

<50x3 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>

# we have a sparse matrix of name final_state we need to convert it into array
for this we use
     -->>  toarray function

In [53]:
final_state = state_dummy.toarray()

In [54]:
type(final_state)

numpy.ndarray

In [55]:
X = N.concatenate((X, final_state),axis=1)

In [56]:
X

array([[165349.2, 136897.8, 471784.1, 0.0, 0.0, 1.0],
       [162597.7, 151377.59, 443898.53, 1.0, 0.0, 0.0],
       [153441.51, 101145.55, 407934.54, 0.0, 1.0, 0.0],
       [144372.41, 118671.85, 383199.62, 0.0, 0.0, 1.0],
       [142107.34, 91391.77, 366168.42, 0.0, 1.0, 0.0],
       [131876.9, 99814.71, 362861.36, 0.0, 0.0, 1.0],
       [134615.46, 147198.87, 127716.82, 1.0, 0.0, 0.0],
       [130298.13, 145530.06, 323876.68, 0.0, 1.0, 0.0],
       [120542.52, 148718.95, 311613.29, 0.0, 0.0, 1.0],
       [123334.88, 108679.17, 304981.62, 1.0, 0.0, 0.0],
       [101913.08, 110594.11, 229160.95, 0.0, 1.0, 0.0],
       [100671.96, 91790.61, 249744.55, 1.0, 0.0, 0.0],
       [93863.75, 127320.38, 249839.44, 0.0, 1.0, 0.0],
       [91992.39, 135495.07, 252664.93, 1.0, 0.0, 0.0],
       [119943.24, 156547.42, 256512.92, 0.0, 1.0, 0.0],
       [114523.61, 122616.84, 261776.23, 0.0, 0.0, 1.0],
       [78013.11, 121597.55, 264346.06, 1.0, 0.0, 0.0],
       [94657.16, 145077.58, 282574.31, 0.

In [57]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [58]:
model.coef_

array([ 8.06023114e-01, -2.70043196e-02,  2.69798610e-02, -5.23005912e+01,
        1.46488202e+02, -9.41876104e+01])

# Now we have three extra columns added to our data set which increases the computation time
but we can observe that in final state if the first two features are 0 then the last feature is 1 so to decrease the computation time we can remove the last feature of the final state 

In [59]:
X.shape

(50, 6)

In [64]:
X= X[:,0:5]

In [65]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [66]:
model.coef_

array([ 8.06023114e-01, -2.70043196e-02,  2.69798610e-02,  4.18870191e+01,
        2.40675812e+02])

In [67]:
X

array([[165349.2, 136897.8, 471784.1, 0.0, 0.0],
       [162597.7, 151377.59, 443898.53, 1.0, 0.0],
       [153441.51, 101145.55, 407934.54, 0.0, 1.0],
       [144372.41, 118671.85, 383199.62, 0.0, 0.0],
       [142107.34, 91391.77, 366168.42, 0.0, 1.0],
       [131876.9, 99814.71, 362861.36, 0.0, 0.0],
       [134615.46, 147198.87, 127716.82, 1.0, 0.0],
       [130298.13, 145530.06, 323876.68, 0.0, 1.0],
       [120542.52, 148718.95, 311613.29, 0.0, 0.0],
       [123334.88, 108679.17, 304981.62, 1.0, 0.0],
       [101913.08, 110594.11, 229160.95, 0.0, 1.0],
       [100671.96, 91790.61, 249744.55, 1.0, 0.0],
       [93863.75, 127320.38, 249839.44, 0.0, 1.0],
       [91992.39, 135495.07, 252664.93, 1.0, 0.0],
       [119943.24, 156547.42, 256512.92, 0.0, 1.0],
       [114523.61, 122616.84, 261776.23, 0.0, 0.0],
       [78013.11, 121597.55, 264346.06, 1.0, 0.0],
       [94657.16, 145077.58, 282574.31, 0.0, 0.0],
       [91749.16, 114175.79, 294919.57, 0.0, 1.0],
       [86419.7, 153514.1